### ISSUE TITLE
Leaderboard submission

### ISSUE THREAD

**Issue by kangalio** [KoleckOLP/Nothing#3]
- Spacebar
- single finger, switched finger a few times during run
- Cherry MX Brown, Qpad MK-50
- Release 1.1.1.0
![image](https://user-images.githubusercontent.com/21220820/117024306-29eafe80-acfa-11eb-9a87-dff13c60ca16.png)

**Comment by KoleckOLP** [comment]
Beautiful so your time is now on my leaderboard :)
